package com.example.hfspring.Model;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.id
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.orgname
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.address
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    public Organization(Integer id, String orgname, String address) {
        this.id = id;
        this.orgname = orgname;
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    public Organization() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.id
     *
     * @return the value of organization.id
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.id
     *
     * @param id the value for organization.id
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.orgname
     *
     * @return the value of organization.orgname
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.orgname
     *
     * @param orgname the value for organization.orgname
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.address
     *
     * @return the value of organization.address
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.address
     *
     * @param address the value for organization.address
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}