package com.example.hfspring.Model;

import java.util.Date;

public class Relics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.id
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.name
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.onSalesTime
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    private Date onsalestime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.photo
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.details
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    private String details;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.value
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.verified
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    private Boolean verified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.poster
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    private String poster;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public Relics(Integer id, String name, Date onsalestime, String photo, String details, Integer value, Boolean verified, String poster) {
        this.id = id;
        this.name = name;
        this.onsalestime = onsalestime;
        this.photo = photo;
        this.details = details;
        this.value = value;
        this.verified = verified;
        this.poster = poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public Relics() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.id
     *
     * @return the value of relics.id
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.id
     *
     * @param id the value for relics.id
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.name
     *
     * @return the value of relics.name
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.name
     *
     * @param name the value for relics.name
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.onSalesTime
     *
     * @return the value of relics.onSalesTime
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public Date getOnsalestime() {
        return onsalestime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.onSalesTime
     *
     * @param onsalestime the value for relics.onSalesTime
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public void setOnsalestime(Date onsalestime) {
        this.onsalestime = onsalestime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.photo
     *
     * @return the value of relics.photo
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.photo
     *
     * @param photo the value for relics.photo
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.details
     *
     * @return the value of relics.details
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.details
     *
     * @param details the value for relics.details
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.value
     *
     * @return the value of relics.value
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.value
     *
     * @param value the value for relics.value
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.verified
     *
     * @return the value of relics.verified
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public Boolean getVerified() {
        return verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.verified
     *
     * @param verified the value for relics.verified
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.poster
     *
     * @return the value of relics.poster
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public String getPoster() {
        return poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.poster
     *
     * @param poster the value for relics.poster
     *
     * @mbg.generated Tue Apr 23 15:39:11 CST 2019
     */
    public void setPoster(String poster) {
        this.poster = poster == null ? null : poster.trim();
    }
}