package com.example.hfspring.Model;

import java.util.Date;

public class Relics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabsystem..relics.id
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabsystem..relics.name
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabsystem..relics.onSalesTime
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    private Date onsalestime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabsystem..relics.photo
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabsystem..relics.details
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..relics
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public Relics(Integer id, String name, Date onsalestime, String photo, String details) {
        this.id = id;
        this.name = name;
        this.onsalestime = onsalestime;
        this.photo = photo;
        this.details = details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..relics
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public Relics() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabsystem..relics.id
     *
     * @return the value of fabsystem..relics.id
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabsystem..relics.id
     *
     * @param id the value for fabsystem..relics.id
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabsystem..relics.name
     *
     * @return the value of fabsystem..relics.name
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabsystem..relics.name
     *
     * @param name the value for fabsystem..relics.name
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabsystem..relics.onSalesTime
     *
     * @return the value of fabsystem..relics.onSalesTime
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public Date getOnsalestime() {
        return onsalestime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabsystem..relics.onSalesTime
     *
     * @param onsalestime the value for fabsystem..relics.onSalesTime
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public void setOnsalestime(Date onsalestime) {
        this.onsalestime = onsalestime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabsystem..relics.photo
     *
     * @return the value of fabsystem..relics.photo
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabsystem..relics.photo
     *
     * @param photo the value for fabsystem..relics.photo
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabsystem..relics.details
     *
     * @return the value of fabsystem..relics.details
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabsystem..relics.details
     *
     * @param details the value for fabsystem..relics.details
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}