package com.example.hfspring.Model;

import java.util.Date;

public class UserInfo {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sex
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.createtime
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.organization
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    private String organization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.address
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.telephone
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.avatar
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.balance
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    private Integer balance;

    public UserInfo(String name, String sex, String createtime, String organization, String address, String telephone, String avatar, Integer balance) {
        this.name = name;
        this.sex = sex;
        this.createtime = createtime;
        this.organization = organization;
        this.address = address;
        this.telephone = telephone;
        this.avatar = avatar;
        this.balance = balance;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getCreatetime() {
        return createtime;
    }

    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    public String getOrganization() {
        return organization;
    }

    public void setOrganization(String organization) {
        this.organization = organization;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getBalance() {
        return balance;
    }

    public void setBalance(Integer balance) {
        this.balance = balance;
    }
/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updatetime
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
}
