package com.example.hfspring.Dao;

import com.example.hfspring.Model.Organization;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "OrgDao")
public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..organization
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..organization
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..organization
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    Organization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..organization
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    List<Organization> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..organization
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    int updateByPrimaryKey(Organization record);

    Organization getOrgFromOrgName(String name);

    boolean updateByOrgName(Organization record);


}