package com.example.hfspring.Dao;

import com.example.hfspring.Model.Relics;
import com.sun.org.apache.xpath.internal.operations.Bool;
import org.springframework.stereotype.Component;

import java.util.List;

@Component("RelicsMapper")
public interface RelicsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Tue Apr 02 10:22:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Tue Apr 02 10:22:06 CST 2019
     */
    int insert(Relics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Tue Apr 02 10:22:06 CST 2019
     */
    Relics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Tue Apr 02 10:22:06 CST 2019
     */
    List<Relics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Tue Apr 02 10:22:06 CST 2019
     */
    int updateByPrimaryKey(Relics record);

    Relics getRelicsByName(String name);

    Boolean isVarified(String name);

    List<Relics> selectByVarified();

    int deleteByName(String name);

    int updateVal(Relics relics);

    int updateVarified(Relics relics);

    String updatePhoto(Relics relics);


    int removeRelics(String name);

    int updateByName(Relics relics);
}