package com.example.hfspring.Dao;

import com.example.hfspring.Model.Relics;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "relicsDao")
public interface RelicsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..relics
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..relics
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    int insert(Relics record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..relics
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    Relics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..relics
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    List<Relics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..relics
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    int updateByPrimaryKey(Relics record);


}