package com.example.hfspring.Dao;

import com.example.hfspring.Model.Role;
import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 15 10:14:11 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Mar 15 10:14:11 CST 2019
     */
    List<Role> selectAll();
}