package com.example.hfspring.Dao;

import com.example.hfspring.Model.Users;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;


@Mapper
@Component(value = "userDao")
public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..users
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..users
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..users
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    Users selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..users
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    List<Users> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabsystem..users
     *
     * @mbg.generated Tue Mar 12 10:35:11 CST 2019
     */
    int updateByPrimaryKey(Users record);

    String getUserPassword(String name);

    Users getUsersFromUsername(String name);

    boolean updateByUserName(Users users);




}