package com.example.hfspring.Dao;

import com.example.hfspring.Model.UserVerify;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "userVerifyDao")
public interface UserVerifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userVerify
     *
     * @mbg.generated Fri Mar 15 10:14:11 CST 2019
     */
    int insert(UserVerify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userVerify
     *
     * @mbg.generated Fri Mar 15 10:14:11 CST 2019
     */
    List<UserVerify> selectAll();

    int updatePassword(UserVerify record);

    void deleteUsers(Integer id);

    void getPassword(String userName);


}