package com.example.hfspring.Dao;

import com.example.hfspring.Model.UserRole;
import java.util.List;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Fri Mar 15 10:14:11 CST 2019
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Fri Mar 15 10:14:11 CST 2019
     */
    List<UserRole> selectAll();
}