package com.example.hfspring.Dao;

import com.example.hfspring.Model.Users;
import org.springframework.stereotype.Component;

import java.util.List;


@Component("UserMapper")
public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    Users selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    List<Users> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon Mar 25 20:08:08 CST 2019
     */
    int updateByPrimaryKey(Users record);

    String getUserPassword(String username);

    int getUserBalance(String username);

    int updatePersonalInfo(Users record);

    int updateBalance(Users record);

    int updatePassword(Users record);

    Users selectByName(String name);

    int updateAvatar(Users users);

    String getUserAvatar(String name);

}